name: srishti
description: "Srishti: The Intelligent Creation Engine."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For Supabase integration (database, auth, storage)
  supabase_flutter: ^2.5.3

  # For loading environment variables from the .env file
  flutter_dotenv: ^5.1.0

  # For state management
  flutter_riverpod: ^2.5.1

  # For elegant and modern fonts
  google_fonts: ^6.2.1
  drag_and_drop_lists: ^0.4.2
  flutter_syntax_view: ^4.1.7
  flutter_markdown: ^0.7.7+1
  webview_flutter: ^4.0.0
  webview_flutter_web: ^0.2.2+1
  xterm: ^4.0.0
  intl: ^0.18.1
  resizable_widget: ^1.0.5
  flutter_code_editor: ^0.3.0
  provider: ^6.0.5
  uuid: ^4.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Bold.ttf
          weight: 700
